social/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostEditView,
    PostDeleteView,
    CommentDeleteView,
    CommentReplyView,
    ProfileView,
    ProfileEditView,
    ProfileDeleteView,
    AddFollower,
    RemoveFollower,
    AddLike,
    AddCommentLike,
    UserSearch,
)

urlpatterns = [
    path('post/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/edit/<int:pk>', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name='post-delete'),
    path(
        'post/<int:post_pk>/comment/delete/<int:pk>/',
        CommentDeleteView.as_view(),
        name='comment-delete'
    ),
    path(
        'post/<int:post_pk>/comment/<int:pk>/reply/',
        CommentReplyView.as_view(),
        name='comment_reply'
    ),
    path('likepost/<int:pk>/', AddLike.as_view(), name='like'),
    path(
        'likecomment/<int:comment_pk>/',
        AddCommentLike.as_view(),
        name='comment-like'
    ),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path(
        'profile/edit/<int:pk>/',
        ProfileEditView.as_view(),
        name='profile-edit'
    ),
    path(
        'profile/<int:pk>/delete/',
        ProfileDeleteView.as_view(),
        name='delete-profile'
    ),
    path(
        'profile/<int:pk>/followers/add',
        AddFollower.as_view(),
        name='add-follower'
    ),
    path(
        'profile/<int:pk>/followers/remove',
        RemoveFollower.as_view(),
        name='remove-follower'
    ),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('', PostListView.as_view(), name='post-list'),
]

xplorer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('account/', include('allauth.urls')),
    path('social/', include('social.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'landing.views.error_400'
handler403 = 'landing.views.error_403'
handler404 = 'landing.views.error_404'
handler500 = 'landing.views.error_500'

social/models.py
import os
from datetime import date, timedelta
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from cloudinary.uploader import destroy
from django.core.files import File
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError


class Post(models.Model):
    """Represents a user's post with text content, an optional image,
    creation date, author, and likes from other users."""
    body = models.CharField(max_length=80)
    image = CloudinaryField('post_image', null=True, blank=True)
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='post_author')
    likes = models.ManyToManyField(User, blank=True, related_name='likes')

    def delete(self, *args, **kwargs):
        """Ensure image associated with post is deleted from Cloudinary."""
        if self.image:
            public_id = self.image.public_id
            destroy(public_id)
        super(Post, self).delete(*args, **kwargs)

    def __str__(self):
        return f"Post by {self.author.username} on {self.created_on.date()}"


class Comment(models.Model):
    """Represents a comment on a post. Each comment has text content,
    creation date, author, associated post, likes, and may be
    a reply to another comment."""
    comment = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    likes = models.ManyToManyField(
        User, blank=True, related_name='comment_likes'
    )
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='+'
    )

    @property
    def children(self):
        """Returns all child comments for the current comment."""
        return (Comment.objects.filter(parent=self)
                .order_by('-created_on')
                .all())

    @property
    def is_parent(self):
        """Check if the current comment is a top-level comment."""
        return self.parent is None

    def __str__(self):
        return f"Comment by {self.author.username} on {self.created_on.date()}"


def validate_age(value):
    """Validate age based on provided date of birth."""
    today = date.today()
    age = (today.year - value.year -
           ((today.month, today.day) < (value.month, value.day)))
    if age < 16 or value > today:
        raise ValidationError('Users must be 16 years old or older.')


class UserProfile(models.Model):
    """Represents additional profile data for a user."""
    user = models.OneToOneField(
        User,
        primary_key=True,
        verbose_name='user',
        related_name='profile',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=10, blank=True, null=True)
    bio = models.TextField(max_length=40, blank=True, null=True)
    date_of_birth = models.DateField(
        null=True, blank=True, validators=[validate_age]
    )
    location = models.CharField(max_length=50, blank=True, null=True)
    picture = CloudinaryField('profile_image', default='user-default_zft92h')
    followers = models.ManyToManyField(
        User, blank=True, related_name='followers'
    )

    def __str__(self):
        return f"Profile of {self.user.username}"


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a user profile when a new user is created."""
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """Save the user profile whenever the user is saved."""
    instance.profile.save()

social/views.py
from datetime import date
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q, Max
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib import messages
from django.views import View
from django.core.paginator import Paginator
from .models import Post, Comment, UserProfile
from .forms import PostForm, CommentForm, UserProfileForm
from django.views.generic.edit import UpdateView, DeleteView


class PostListView(LoginRequiredMixin, View):
    """
    PostListView:
    - Displays a list of posts from users that the current user follows.
    - Allows the current user to create a new post.
    """

    def get_newsfeed_posts(self, user):
        followed_profiles = UserProfile.objects.filter(followers__in=[user])
        followed_users = [profile.user for profile in followed_profiles]

        # Include posts from the user as well
        followed_users.append(user)

        # Get latest posts from followed users and the user themselves
        posts = Post.objects.filter(author__in=followed_users).order_by('-created_on')

        return posts

    def get(self, request, *args, **kwargs):
        posts = self.get_newsfeed_posts(request.user)
        paginator = Paginator(posts, 3)  # 3 posts per page

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        form = PostForm()
        context = {
            'page_obj': page_obj,
            'form': form,
        }
        return render(request, 'post_list.html', context)

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            messages.success(
                request,
                'Your post has been created! 🎉'
            )
            return redirect('post-list')

        posts = self.get_newsfeed_posts(request.user)
        paginator = Paginator(posts, 3)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'page_obj': page_obj,
            'form': form,
        }
        return render(request, 'post_list.html', context)


class PostDetailView(LoginRequiredMixin, View):
    """
    PostDetailView:
    - Displays the details of a specific post.
    - Allows users to view comments and add new ones to the post.
    """
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm()
        comments = Comment.objects.filter(post=post, parent=None).order_by('-created_on')
        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }

        return render(request, 'post_detail.html', context)
    
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request, 'Your comment has been added!')

        comments = Comment.objects.filter(post=post, parent=None)\
                          .order_by('-created_on')
        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }

        return render(request, 'post_detail.html', context)


class CommentReplyView(LoginRequiredMixin, View):
    """
    CommentReplyView:
    - Allows users to reply to specific comments on a post.
    - Associates the new comment with the parent comment, post, and the user.
    """
    def post(self, request, post_pk, pk, *args, **kwargs):
        post = Post.objects.get(pk=post_pk)
        parent_comment = Comment.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.parent = parent_comment
            new_comment.save()

        return redirect('post-detail', pk=post.pk)


class PostEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    PostEditView:
    - Allows post authors to edit their own posts.
    - Uses the UpdateView to provide form handling for editing the post's body.
    - Tests if the user trying to edit the post is indeed its author.
    """
    model = Post
    fields = ['body']
    template_name = 'post_edit.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('post-detail', kwargs={'pk': pk})

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
    def form_valid(self, form):
        messages.success(self.request, 'Your post has been updated!')
        return super().form_valid(form)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    PostDeleteView:
    - Allows post authors to delete their own posts.
    - Uses the DeleteView for deleting posts and redirects
    - to the post list after deletion.
    - Tests if the user trying to delete the post is indeed its author.
    """
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post-list')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Your post has been deleted.')
        return super().delete(request, *args, **kwargs)


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    CommentDeleteView:
    - Allows comment authors to delete their own comments.
    - Uses the DeleteView for deleting comments and redirects
    - to the post detail after deletion.
    - Tests if the user trying to delete the comment is indeed its author.
    """
    model = Comment
    template_name = 'comment_delete.html'

    def get_success_url(self):
        pk = self.kwargs['post_pk']
        return reverse_lazy('post-detail', kwargs={'pk': pk})

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
    
    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Comment deleted successfully.')
        return super().delete(request, *args, **kwargs)


class ProfileView(View):
    """
    ProfileView:
    - Displays details of a specific user's profile.
    - Shows the user's posts, followers, and checks
    - if the current user is following the profile.
    - Calculates and displays the age of the user if the
    - date of birth is provided.
    """
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(user=pk)
        user = profile.user
        posts = Post.objects.filter(author=user).order_by('-created_on')
        followers = profile.followers.all()

        if len(followers) == 0:
            is_following = False

        for follower in followers:
            if follower == request.user:
               is_following = True
               break
            else:
                is_following = False

        number_of_followers = len(followers)

        if profile.date_of_birth:
            age = date.today().year - profile.date_of_birth.year - ((date.today().month, date.today().day) < (profile.date_of_birth.month, profile.date_of_birth.day))
        else:
            age = None

        context = {
            'user': user,
            'profile': profile,
            'posts': posts,
            'number_of_followers': number_of_followers,
            'is_following': is_following,
            'age': age,
        }

        return render(request, 'profile.html', context)


class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    ProfileEditView:
    - Allows users to edit their own profiles.
    - Uses the UpdateView to provide form handling for editing the profile.
    - Tests if the user trying to edit the profile is indeed its owner.
    """
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'profile_edit.html'

    def get_success_url(self):
        pk= self.kwargs['pk']
        return reverse_lazy('profile', kwargs={'pk': pk})

    def test_func(self):
        profile = self.get_object()
        return self.request.user == profile.user
    
    def form_valid(self, form):
        messages.success(self.request, 'Your profile has been updated!')
        return super().form_valid(form)


class ProfileDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    ProfileDeleteView:
    - Allows users to delete their own profiles.
    - Upon profile deletion, logs out the user and deletes the user account.
    - Uses the DeleteView for deleting profiles.
    """
    model = UserProfile
    template_name = 'profile_delete.html'
    success_url = reverse_lazy('index')

    def test_func(self):
        profile = self.get_object()
        return self.request.user == profile.user

    def delete(self, request, *args, **kwargs):
        user = self.request.user
        response = super().delete(request, *args, **kwargs)
        logout(request)
        user.delete()
        messages.success(request, 'Your profile has been deleted!')
        return response


class AddFollower(LoginRequiredMixin, View):
    """
    AddFollower:
    - Allows users to follow another user's profile.
    """
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        profile.followers.add(request.user)

social/templates/child_comments.html
{% for child_comment in comment.children %}
<div class="mt-3 mb-1 child-comment pl-4">
    <!-- Child Comment Header -->
    <div>
        <div class="d-flex justify-content-between align-items-center">
            
            <!-- Child Comment Author's Profile Picture and Name -->
            <div class="d-flex align-items-center">
                <a href="{% url 'profile' child_comment.author.profile.pk %}">
                    <img 
                        class="rounded-circle post-img mr-2" 
                        height="30" width="30" 
                        src="{{ child_comment.author.profile.picture.url }}"
                        alt="{{ child_comment.author }}'s profile picture">
                </a>
                <p class="post-text mb-0">
                    <a class="text-primary post-link" href="{% url 'profile' child_comment.author.profile.pk %}">
                        {{ child_comment.author }}
                    </a>
                </p>
                <span class="ms-1 posted-on-text">{{ child_comment.created_on }}</span>
            </div>

            <!-- Child Comment Delete Option -->
            {% if request.user == child_comment.author %}
            <a href="{% url 'comment-delete' post.pk child_comment.pk %}" class="bin-color" aria-label="Delete Reply">
                <i class="fas fa-trash"></i>
            </a>
            {% endif %}
        </div>

        <!-- Child Comment Body -->
        <p class="mt-4 ps-1">{{ child_comment.comment }}</p>

        <!-- Child Comment Like Action -->
        <div class="d-flex flex-row">
            <form id="comment-like-form-{{ child_comment.pk }}" method="POST" action="{% url 'comment-like' child_comment.pk %}">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button class="like-btn {% if user in child_comment.likes.all %}liked{% endif %}" type="button" onclick="likeComment('{{ child_comment.pk }}')" aria-label="Like Reply">
                    <i class="{% if user in child_comment.likes.all %}fas{% else %}far{% endif %} fa-heart"></i> <span id="comment-like-count-{{ child_comment.pk }}">{{ child_comment.likes.all.count }}</span>
                </button>
            </form>            
            
        </div>
    </div>
</div>
{% endfor %}

social/templates/comment_delete.html
{% extends 'base_grid.html' %}

{% block grid_content %}

<div class="post-container mt-4">
    <!-- Back Button Row -->
    <div class="mt-2">

            <!-- Back to Post Button -->
            <a href="{% url 'post-detail' object.post.pk %}">
                <button class="btn btn-dark w-100" aria-label="Go back to the post">
                    <i class="fa-regular fa-circle-left" style="color: white;" aria-hidden="true"></i> Back to Post
                </button>
            </a>
    </div>

    <!-- Delete Confirmation Row -->
    <div class="post-container-light mt-3">
        <div class="mt-3 mb-3">
            
                <!-- Delete Confirmation Form -->
                <form method="POST">
                    {% csrf_token %}
                    <h5>Are you sure?</h5>
                    <p>Deleting comment cannot be undone!</p>
                    
                    <!-- Delete Button Container -->
                    <div class="d-grid gap-2">
                        <button class="btn btn-danger mt-3" aria-label="Confirm deletion of the comment">Delete</button>
                    </div>
                </form>
        </div>
    </div>
</div>
{% endblock grid_content %}

social/templates/comments.html
{% load crispy_forms_tags %}
{% load static %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 position-relative">

            <!-- Main Post Container -->
            <div class="post-container border-top">

                <!-- Comment Input Form -->
                <form method="POST" class="mt-2">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="d-grid gap-2">
                        <button class="btn btn-success mt-3" aria-label="Submit Comment">Comment</button>
                    </div>
                </form>

                {% if comments %}
                <!-- Toggle Comments Button -->
                <button 
                    class="remove-default-btn mt-3"
                    onclick="commentToggle('{{post.pk}}')" 
                    aria-label="Toggle Comments">
                    View Comments
                </button>
                {% endif %}

                <!-- Comments List -->
                <div class="d-none mt-2" id="comments-{{ post.pk }}" aria-label="Comments Section">

                    <!-- Loop through each comment -->
                    {% for comment in comments %}
                    <div class="mt-3 mb-1" id="{{comment.pk}}">

                        <!-- Comment Header -->
                        <div class="border-bottom">
                            <div class="d-flex justify-content-between align-items-center">
                                <!-- Author's Profile Picture and Name -->
                                <div class="d-flex align-items-center">
                                    <a href="{% url 'profile' comment.author.profile.pk %}">
                                        <img 
                                            class="rounded-circle post-img mr-2" 
                                            height="30" width="30" 
                                            src="{{ comment.author.profile.picture.url }}"
                                            alt="{{ comment.author }}'s profile picture">
                                    </a>
                                    <p class="post-text mb-0">
                                        <a class="text-primary post-link" href="{% url 'profile' comment.author.profile.pk %}">
                                            {{ comment.author }}
                                        </a>
                                
                                    </p>
                                    <span class="ms-1 posted-on-text">{{ comment.created_on }}</span>
                                </div>

                                <!-- Delete Option -->
                                {% if request.user == comment.author %}
                                <a href="{% url 'comment-delete' post.pk comment.pk %}" class="bin-color" aria-label="Delete Comment">
                                    <i class="fas fa-trash"></i>
                                </a>
                                {% endif %}
                            </div>

                            <!-- Comment Body -->
                            <div class="post-container-light mt-2">
                            <p>{{ comment.comment }}</p>

                            <!-- Comment Actions (Like and Reply) -->
                            <div class="d-flex flex-row">

                                <!-- Like and Reply Action Wrapper -->
                                <div class="d-flex flex-row align-items-start">

                                    <!-- Like Action -->
                                    <form id="comment-like-form-{{ comment.pk }}" method="POST" action="{% url 'comment-like' comment.pk %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <button class="like-btn {% if user in comment.likes.all %}liked{% endif %}" type="button" onclick="likeComment('{{ comment.pk }}')" aria-label="Like Comment">
                                            <i class="{% if user in comment.likes.all %}fas{% else %}far{% endif %} fa-heart"></i> <span id="comment-like-count-{{ comment.pk }}">{{ comment.likes.all.count }}</span>
                                        </button>
                                    </form>                                    
                                    
                                    <!-- Reply Action Icon -->
                                    <button 
                                        class="remove-default-btn comment-btn" 
                                        onclick="commentReplyToggle('{{comment.pk}}')" 
                                        aria-label="Reply to Comment">
                                        <i class="far fa-comment-dots"></i>
                                    </button>
                                </div>
                            </div>
                            </div>

                            <!-- Reply Input Form -->
                            <div class="reply-input d-none mt-1" id="reply-input-{{comment.pk}}">
                                <form method="POST" action="{% url 'comment_reply' post.pk comment.pk %}">
                                    {% csrf_token %}
                                    {{ form | crispy }}
                                    <div class="d-grid gap-1">
                                        <button class="btn btn-success mt-3" aria-label="Submit Reply">Reply</button>
                                    </div>
                                </form>
                            </div>

                            {% include 'child_comments.html' %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

social/templates/post_delete.html
{% extends 'base_grid.html' %}

{% block grid_content %}

<div class="post-container-light mt-4">
    <!-- Back Button Row -->
    <div class="mt-2">

            <!-- Back to Post Button -->
            <a href="{% url 'post-detail' object.pk %}">
                <button class="btn btn-dark w-100" aria-label="Go back to the post">
                    <i class="fa-regular fa-circle-left" style="color: white;" aria-hidden="true"></i> Back to Post
                </button>
            </a>
    </div>

    <!-- Delete Confirmation Row -->
    <div class="post-container mt-3">
        <div class=" mt-3 mb-3">

                <!-- Delete Confirmation Form -->
                <form method="POST">
                    
                    {% csrf_token %}
                    <h5>Are you sure?</h5>
                    <p>Deleting post cannot be undone!</p>
                
                    <!-- Delete Button Container -->
                    <div class="d-grid gap-2">
                        <button class="btn btn-danger mt-3" aria-label="Confirm deletion of the post">Delete</button>
                    </div>
                </form>
        </div>
    </div>
</div>
{% endblock grid_content %}

social/templates/post_detail.html
{% extends 'base_grid.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block grid_content %}

    <!-- Back Button Row -->
    <div class="mt-2">
        <a href="{% url 'post-list' %}">
        <button class="btn btn-dark w-100" aria-label="Add a new post">
            <i class="fa-regular fa-circle-left" style="color: white;"></i> Back to Feed
        </button>
        </a>
    </div>

    <!-- Post Display Section -->
    <div class="mt-3">
        <div class="border-bottom post-container">
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <a href="{% url 'profile' post.author.profile.pk %}">
                        <img class=" rounded-circle post-img mr-2" height="40" width="40" src="{{ post.author.profile.picture.url }}"/>
                    </a>
                    <p class="post-text mb-0">
                        <a class="text-primary" href="{% url 'profile' post.author.profile.pk %}">{{ post.author }}</a>
                    </p>
                    <span class="ms-1 posted-on-text">{{ post.created_on }}</span>
                </div>
                {% if request.user == post.author %}
                    <div>
                        <a href="{% url 'post-edit' post.pk %}" class="edit-color mr-2"><i class="far fa-edit"></i></a>
                        <a href="{% url 'post-delete' post.pk %}" class="bin-color"><i class="fas fa-trash"></i></a>
                    </div>
                {% endif %}
            </div>
            <div class="post-body mt-2">

                {% if post.image %}
                    <img src="{{ post.image.url }}" class="post-image img-fluid mt-3"/>
                {% endif %}    
                <p class="text-center p-2">{{ post.body }}</p>
            </div>
            
            <div class="d-flex flex-row">
                <!-- Likes button -->
                <form id="like-form-{{ post.pk }}" method="POST" action="{% url 'like' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="like-btn {% if user in post.likes.all %}liked{% endif %}" type="button" onclick="likePost('{{ post.pk }}')" aria-label="Like this post">
                        <i class="{% if user in post.likes.all %}fas{% else %}far{% endif %} fa-heart"></i> <span id="like-count-{{ post.pk }}">{{ post.likes.all.count }}</span>
                    </button>                                                
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Include Comments Section -->
{% include "comments.html" %}

{% endblock grid_content %}

social/templates/profile_edit.html
{% extends 'base_grid.html' %}
{% load crispy_forms_tags %}

{% block grid_content %}

<!-- Navigation Section -->

<div class="mt-2">
    <!-- Back to Profile Button -->
    <a href="{% url 'profile' object.pk %}">
        <button class="btn btn-dark w-100" aria-label="Return to profile">
            <i class="fa-regular fa-circle-left" style="color: white;" aria-hidden="true"></i> Back to Profile
        </button>
    </a>
</div>

<div class="post-container mt-4">

    <!-- Edit Profile Header -->
    <div class="mt-3">
           <h5>Edit Profile</h5> 
    </div>

    <!-- Edit Profile Form -->
    <div class="mt-3 mb-3">

        <!-- Form to Edit User Profile -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            
            <!-- Submit Button -->
            <div class="d-grid gap-2">
                <button class="btn btn-success mt-3" aria-label="Submit profile changes">Submit</button>
            </div>
        </form>
        
        <!-- Delete Profile Form -->
        <div class="d-grid gap-2">
            <a href="{% url 'delete-profile' object.pk %}" class="btn btn-danger mt-3" aria-label="Delete profile">Delete Profile</a>
        </div>
    </div>
    
</div>

<script>
    setTimeout(function() {
    $(document).ready(function() {
        $('#id_location').select2();
    });
}, 1000);  // waits 1 second before running the script
</script>

{% endblock grid_content %}